{% set name = "ewah-bool-utils" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ewah_bool_utils-{{ version }}.tar.gz
  sha256: 7050b5a25f4df14f05f8898fd9e797cd0a0f7103207c618e0467a450d3dee987
  patches:
    - patches/crossc-openmp.patch  # [linux]

build:
  skip: true  # [py<39 or python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libgomp                                # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ewah_bool_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ewah-bool-utils/
  summary: EWAH Bool Array utils for yt
  license: Apache-2.0 & BSD-3-Clause
  license_file:
    - LICENSE
    - ewah_bool_utils/cpp/LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
    - matthewturk
