{% set name = "ewah-bool-utils" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
  sha256: eb901f46caef189de3a0c1f5ca06287cfaba7976ddf76fa1c1f3bce1b60b7ac3
  patches:    # [win]
    - patches/0001-fix-openmp-test-linking-on-windows.patch   # [win]

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp    # [not linux]
    - m2-patch       # [win]
  host:
    - python
    - cython >=3.0
    - numpy >=2.0.0
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.19.3,<3

test:
  source_files:
    - ewah_bool_utils/tests
  imports:
    - ewah_bool_utils
  commands:
    - pip check
    - pytest -v
  requires:
    - pip
    - pytest

about:
  home: https://pypi.org/project/ewah-bool-utils/
  summary: EWAH Bool Array utils for yt
  description: EWAH Bool Array utils for yt
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - ewah_bool_utils/cpp/LICENSE
  license_family: OTHER
  doc_url: https://pypi.org/project/ewah-bool-utils/
  dev_url: https://github.com/yt-project/ewah_bool_utils/

extra:
  recipe-maintainers:
    - neutrinoceros
    - matthewturk
