{% set name = "ewah-bool-utils" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ewah_bool_utils-{{ version }}.tar.gz
  sha256: eb901f46caef189de3a0c1f5ca06287cfaba7976ddf76fa1c1f3bce1b60b7ac3
  patches:
    - patches/crossc-openmp.patch  # [linux]

build:
  skip: true  # [py<39 or python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libgomp                                # [linux]
    - setuptools
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - numpy
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - ewah_bool_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ewah-bool-utils/
  summary: EWAH Bool Array utils for yt
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - ewah_bool_utils/cpp/LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
    - matthewturk
